# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BluedolphinCloudSdk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'RealmSwift'
pod 'AlamofireObjectMapper'
pod 'AWSS3'
  # Pods for BluedolphinCloudSdk

end
