# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bdPresence' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bdPresence
pod 'Alamofire'
pod 'AlamofireObjectMapper'
pod 'AWSS3'
pod 'RealmSwift'
pod 'IQKeyboardManagerSwift'
pod 'Fabric'
pod 'Crashlytics'
pod 'ReachabilitySwift', '~> 3'
  target 'bdPresenceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bdPresenceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
