# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bdAttendence' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bdAttendence
pod 'Alamofire'
pod 'AlamofireObjectMapper'
pod 'AWSS3'
pod 'RealmSwift','~> 2.0.2'
  target 'bdAttendenceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bdAttendenceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
