// Generated by Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import Photos;
@import RealmSwift;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BluedolphinCloudSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class RLMRealm;
@class RLMObjectSchema;
@class RLMSchema;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk17AccessTokenObject")
@interface AccessTokenObject : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable organizationId;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable organizationName;
@property (nonatomic) NSInteger expires;
@property (nonatomic, copy) NSString * _Nullable userName;
@property (nonatomic, copy) NSString * _Nullable orgFeatures;
@property (nonatomic, copy) NSString * _Nullable privelege;
@property (nonatomic, copy) NSString * _Nullable userMetas;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk16AssignmentHolder")
@interface AssignmentHolder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk15AssignmentModel")
@interface AssignmentModel : NSObject
+ (void)getAssignmentsWithAssignmentId:(NSString * _Nonnull)assignmentId completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.getAssignments(assignmentId:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)getAssignmentsForDesiredTimeWithQuery:(NSString * _Nonnull)query completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.getAssignmentsForDesiredTime(query:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)getAssignmentsWithStatus:(NSString * _Nonnull)status completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.getAssignments(status:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)updateAssignments SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.updateAssignments()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)postdbAssignments SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.postdbAssignments()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)postAssignmentsWithAssignment:(NSObject * _Nonnull)assignment SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.postAssignments(assignment:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDictionary;

@interface AssignmentModel (SWIFT_EXTENSION(BluedolphinCloudSdk))
+ (void)createAssignmentWithAssignmentData:(AssignmentHolder * _Nonnull)assignmentData SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.createAssignment(assignmentData:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)saveAssignmentWithAssignmentData:(NSDictionary * _Nonnull)assignmentData SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.saveAssignment(assignmentData:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (BOOL)statusOfUser SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'AssignmentModel.statusOfUser()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk13AttendanceLog")
@interface AttendanceLog : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable dayofWeek;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk10BeaconData")
@interface BeaconData : RealmSwiftObject
@property (nonatomic, copy) NSDate * _Nullable lastSeen;
@property (nonatomic, copy) NSString * _Nullable distance;
@property (nonatomic, copy) NSString * _Nullable rssi;
@property (nonatomic, copy) NSString * _Nullable major;
@property (nonatomic, copy) NSString * _Nullable minor;
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic, copy) NSString * _Nullable beaconId;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable beaconNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class BluedolphinLocationManager;
@class NSMutableDictionary;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk18BlueDolphinManager")
@interface BlueDolphinManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BlueDolphinManager * _Nonnull manager SWIFT_DEPRECATED_OBJC("Swift property 'BlueDolphinManager.manager' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (BlueDolphinManager * _Nonnull)manager SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'BlueDolphinManager.manager' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSString * _Nonnull emailId SWIFT_DEPRECATED_OBJC("Swift property 'BlueDolphinManager.emailId' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) BluedolphinLocationManager * _Null_unspecified bluedolphinLocationManager SWIFT_DEPRECATED_OBJC("Swift property 'BlueDolphinManager.bluedolphinLocationManager' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) NSMutableDictionary * _Nonnull seanbeacons SWIFT_DEPRECATED_OBJC("Swift property 'BlueDolphinManager.seanbeacons' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)initializeWithSecretKey:(NSString * _Nullable)secretKey organizationId:(NSString * _Nullable)organizationId email:(NSString * _Nullable)email firstName:(NSString * _Nullable)firstName lastName:(NSString * _Nullable)lastName metaInfo:(NSDictionary * _Nullable)metaInfo SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.initialize(secretKey:organizationId:email:firstName:lastName:metaInfo:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setConfigWithSecretKey:(NSString * _Nonnull)secretKey organizationId:(NSString * _Nonnull)organizationId SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.setConfig(secretKey:organizationId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)authorizeUserWithEmail:(NSString * _Nonnull)email firstName:(NSString * _Nonnull)firstName lastName:(NSString * _Nonnull)lastName metaInfo:(NSDictionary * _Nonnull)metaInfo completion:(void (^ _Nonnull)(BOOL))completion SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.authorizeUser(email:firstName:lastName:metaInfo:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)postTransientCheckinWithMetaInfo:(NSDictionary<NSString *, id> * _Nonnull)metaInfo SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.postTransientCheckin(metaInfo:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)getNearByBeaconsWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.getNearByBeacons(completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)startScanningWithCompletion:(void (^ _Nonnull)(BOOL))completion SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.startScanning(completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)stopScanning SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.stopScanning()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateToken SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.updateToken()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)stopLocationMonitoring SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.stopLocationMonitoring()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)startLocationMonitoring SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.startLocationMonitoring()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)sendCheckinsWithArray:(NSArray * _Nonnull)array SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.sendCheckins(array:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)gpsAuthorizationStatusWithGpsStatus:(void (^ _Nonnull)(CLAuthorizationStatus))gpsStatus SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.gpsAuthorizationStatus(gpsStatus:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)bluetoothEnabledWithCompletion:(void (^ _Nonnull)(BOOL))completion SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.bluetoothEnabled(completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)toSendBackgroundAppRefreshStateCheckinsWithCurrentStatus:(BOOL)currentStatus SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.toSendBackgroundAppRefreshStateCheckins(currentStatus:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)toSendGPSStateCheckinsWithCurrentStatus:(BOOL)currentStatus SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.toSendGPSStateCheckins(currentStatus:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)toSendBluetoothStateCheckinsWithCurrentStatus:(BOOL)currentStatus SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.toSendBluetoothStateCheckins(currentStatus:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSInteger)getBeaconDataCount SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.getBeaconDataCount()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateOvernightShiftValues SWIFT_DEPRECATED_OBJC("Swift method 'BlueDolphinManager.updateOvernightShiftValues()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocationManager;
@class CLLocation;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk26BluedolphinLocationManager")
@interface BluedolphinLocationManager : NSObject <CLLocationManagerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) BluedolphinLocationManager * _Nonnull sharedInstance SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.sharedInstance' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (BluedolphinLocationManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.sharedInstance' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)setSharedInstance:(BluedolphinLocationManager * _Nonnull)value SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.sharedInstance' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, strong) CLLocationManager * _Nonnull manager SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.manager' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) CLLocationAccuracy acceptableLocationAccuracy SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.acceptableLocationAccuracy' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) NSTimeInterval checkLocationInterval SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.checkLocationInterval' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL isRunning SWIFT_DEPRECATED_OBJC("Swift property 'BluedolphinLocationManager.isRunning' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)requestAlwaysAuthorization SWIFT_DEPRECATED_OBJC("Swift method 'BluedolphinLocationManager.requestAlwaysAuthorization()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)startUpdatingLocationWithInterval:(NSTimeInterval)interval acceptableLocationAccuracy:(CLLocationAccuracy)acceptableLocationAccuracy SWIFT_DEPRECATED_OBJC("Swift method 'BluedolphinLocationManager.startUpdatingLocation(interval:acceptableLocationAccuracy:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)stopUpdatingLocation SWIFT_DEPRECATED_OBJC("Swift method 'BluedolphinLocationManager.stopUpdatingLocation()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)startLocationManager SWIFT_DEPRECATED_OBJC("Swift method 'BluedolphinLocationManager.startLocationManager()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)stopLocationManager SWIFT_DEPRECATED_OBJC("Swift method 'BluedolphinLocationManager.stopLocationManager()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk13CheckinHolder")
@interface CheckinHolder : NSObject
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable accuracy;
@property (nonatomic, copy) NSString * _Nullable altitude;
@property (nonatomic, copy) NSString * _Nullable organizationId;
@property (nonatomic, copy) NSString * _Nullable checkinId;
@property (nonatomic, copy) NSString * _Nullable time;
@property (nonatomic, copy) NSString * _Nullable checkinCategory;
@property (nonatomic, copy) NSString * _Nullable checkinType;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable checkinDetails;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable assignmentId;
@property (nonatomic, copy) NSString * _Nullable imageName;
@property (nonatomic, copy) NSString * _Nullable relativeUrl;
@property (nonatomic, copy) NSString * _Nullable jobNumber;
@property (nonatomic, copy) NSArray * _Nullable beaconProximities;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk12CheckinModel")
@interface CheckinModel : NSObject
+ (NSInteger)getCheckinCount SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CheckinModel.getCheckinCount()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)postCheckinWithCheckinId:(NSString * _Nonnull)checkinId SWIFT_DEPRECATED_OBJC("Swift method 'CheckinModel.postCheckin(checkinId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)createCheckinWithCheckinData:(CheckinHolder * _Nonnull)checkinData SWIFT_DEPRECATED_OBJC("Swift method 'CheckinModel.createCheckin(checkinData:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LocationData;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk11ClusterData")
@interface ClusterData : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable checkInId;
@property (nonatomic, copy) NSString * _Nullable timeSpent;
@property (nonatomic, copy) NSDate * _Nullable startTime;
@property (nonatomic, copy) NSDate * _Nullable endTime;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) LocationData * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable distance;
@property (nonatomic, copy) NSString * _Nullable placeId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end



@class NSString;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk15KeychainService")
@interface KeychainService : NSObject
- (NSString * _Nullable)loadWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'KeychainService.load(name:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk31LocationAttendanceFromServerLog")
@interface LocationAttendanceFromServerLog : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable dayofWeek;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk21LocationAttendanceLog")
@interface LocationAttendanceLog : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable dayofWeek;
@property (nonatomic, copy) NSDate * _Nullable timeStamp;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk12LocationData")
@interface LocationData : RealmSwiftObject
@property (nonatomic, copy) NSDate * _Nullable lastSeen;
@property (nonatomic, copy) NSString * _Nullable accuracy;
@property (nonatomic, copy) NSString * _Nullable altitude;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable organizationId;
@property (nonatomic, copy) NSString * _Nullable checkinId;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable details;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk19LocationHistoryData")
@interface LocationHistoryData : NSObject
+ (void)getTeamMember SWIFT_DEPRECATED_OBJC("Swift method 'LocationHistoryData.getTeamMember()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (NSInteger)getLocationDataCount SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'LocationHistoryData.getLocationDataCount()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)makeAttendanceLogModelWithStatus:(BOOL)status SWIFT_DEPRECATED_OBJC("Swift method 'LocationHistoryData.makeAttendanceLogModel(status:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk11MyTeamModel")
@interface MyTeamModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC19BluedolphinCloudSdk8OTPModel")
@interface OTPModel : NSObject
+ (void)getOtpWithMobile:(NSString * _Nonnull)mobile countryCode:(NSString * _Nonnull)countryCode completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'OTPModel.getOtp(mobile:countryCode:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk10OauthModel")
@interface OauthModel : NSObject
+ (void)getTokenWithUserObject:(NSDictionary<NSString *, id> * _Nonnull)userObject completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'OauthModel.getToken(userObject:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)updateToken SWIFT_DEPRECATED_OBJC("Swift method 'OauthModel.updateToken()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface PHAssetCollection (SWIFT_EXTENSION(BluedolphinCloudSdk))
@property (nonatomic, readonly) NSInteger photosCount SWIFT_DEPRECATED_OBJC("Swift property 'PHAssetCollection.photosCount' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk11PlaceDetail")
@interface PlaceDetail : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable placeId;
@property (nonatomic, copy) NSString * _Nullable editedBy;
@property (nonatomic, copy) NSString * _Nullable addedBy;
@property (nonatomic) float fenceRadius;
@property (nonatomic, copy) NSString * _Nullable placeType;
@property (nonatomic, copy) NSString * _Nullable address;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk21PushNotificationRealm")
@interface PushNotificationRealm : RealmSwiftObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk11RMCAssignee")
@interface RMCAssignee : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable organizationId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class RMCLocation;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk19RMCAssignmentObject")
@interface RMCAssignmentObject : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable assignmentId;
@property (nonatomic, copy) NSDate * _Nullable addedOn;
@property (nonatomic, copy) NSDate * _Nullable time;
@property (nonatomic, copy) NSDate * _Nullable updatedOn;
@property (nonatomic, copy) NSString * _Nullable assignmentDetails;
@property (nonatomic, copy) NSString * _Nullable assignmentStatusLog;
@property (nonatomic, copy) NSDate * _Nullable assignmentDeadline;
@property (nonatomic, copy) NSDate * _Nullable assignmentStartTime;
@property (nonatomic, copy) NSString * _Nullable assignmentAddress;
@property (nonatomic, strong) RMCAssignee * _Nullable assignerData;
@property (nonatomic, strong) RMCLocation * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable jobNumber;
@property (nonatomic, copy) NSString * _Nullable bookmarked;
@property (nonatomic, copy) NSDate * _Nullable lastUpdated;
@property (nonatomic, copy) NSString * _Nullable assignmentType;
@property (nonatomic, copy) NSDate * _Nullable downloadedOn;
@property (nonatomic, copy) NSDate * _Nullable submittedOn;
@property (nonatomic, copy) NSString * _Nullable firstTypeAssignment;
@property (nonatomic, copy) NSString * _Nullable placeId;
@property (nonatomic, copy) NSString * _Nullable localStatus;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk9RMCBeacon")
@interface RMCBeacon : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable lastSeen;
@property (nonatomic, copy) NSString * _Nullable distance;
@property (nonatomic, copy) NSString * _Nullable rssi;
@property (nonatomic, copy) NSString * _Nullable major;
@property (nonatomic, copy) NSString * _Nullable minor;
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic, copy) NSString * _Nullable beaconId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk10RMCDObject")
@interface RMCDObject : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable dObjectId;
@property (nonatomic, copy) NSString * _Nullable dObjectDetails;
@property (nonatomic) BOOL isUploaded;
+ (NSString * _Nonnull)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk12RMCDObjectId")
@interface RMCDObjectId : RealmSwiftObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk17RMCDObjectManager")
@interface RMCDObjectManager : NSObject
+ (void)getDObjectsDetailsWithOrderId:(NSString * _Nonnull)orderId philipsObjectID:(NSString * _Nonnull)philipsObjectID completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'RMCDObjectManager.getDObjectsDetails(orderId:philipsObjectID:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (RMCDObject * _Nullable)getDObjectFromDBWithDobjectId:(NSString * _Nonnull)dobjectId SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'RMCDObjectManager.getDObjectFromDB(dobjectId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)saveDobjectInDBWithDObjectDetails:(NSDictionary * _Nonnull)dObjectDetails dobjectId:(NSString * _Nonnull)dobjectId SWIFT_DEPRECATED_OBJC("Swift method 'RMCDObjectManager.saveDobjectInDB(dObjectDetails:dobjectId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)updateDOBjectWithObjectId:(NSString * _Nonnull)objectId SWIFT_DEPRECATED_OBJC("Swift method 'RMCDObjectManager.updateDOBject(objectId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk11RMCLocation")
@interface RMCLocation : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable altitude;
@property (nonatomic, copy) NSString * _Nullable accuracy;
@property (nonatomic, copy) NSString * _Nullable associationId;
@property (nonatomic, copy) NSString * _Nullable type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk9RMCPhotos")
@interface RMCPhotos : RealmSwiftObject
+ (NSString * _Nonnull)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class RMCPlaceLocation;

SWIFT_CLASS("_TtC19BluedolphinCloudSdk8RMCPlace")
@interface RMCPlace : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable placeId;
@property (nonatomic, copy) NSDate * _Nullable addedOn;
@property (nonatomic, copy) NSDate * _Nullable updatedOn;
@property (nonatomic, copy) NSString * _Nullable placeAddress;
@property (nonatomic, strong) RMCPlaceLocation * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable geoTagName;
@property (nonatomic, copy) NSString * _Nullable associationIds;
@property (nonatomic, copy) NSString * _Nullable localStatus;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, strong) PlaceDetail * _Nullable placeDetails;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk16RMCPlaceLocation")
@interface RMCPlaceLocation : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable placeId;
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable altitude;
@property (nonatomic, copy) NSString * _Nullable accuracy;
@property (nonatomic, copy) NSString * _Nullable associationId;
@property (nonatomic, copy) NSString * _Nullable type;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk16RMCPlacesManager")
@interface RMCPlacesManager : NSObject
+ (void)getPlaces SWIFT_DEPRECATED_OBJC("Swift method 'RMCPlacesManager.getPlaces()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (RMCDObject * _Nullable)getDObjectFromDBWithDobjectId:(NSString * _Nonnull)dobjectId SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'RMCPlacesManager.getDObjectFromDB(dobjectId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)saveDobjectInDBWithStatus:(BOOL)status SWIFT_DEPRECATED_OBJC("Swift method 'RMCPlacesManager.saveDobjectInDB(status:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk7RMCUser")
@interface RMCUser : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable rmcUserShift;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIDevice (SWIFT_EXTENSION(BluedolphinCloudSdk))
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName SWIFT_DEPRECATED_OBJC("Swift property 'UIDevice.modelName' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk17UserAvaiblityData")
@interface UserAvaiblityData : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable isAvailable;
@property (nonatomic, copy) NSDate * _Nullable availableFrom;
@property (nonatomic, copy) NSDate * _Nullable availableTo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk13UserDataModel")
@interface UserDataModel : NSObject
+ (void)userSignUpWithParam:(NSDictionary<NSString *, id> * _Nonnull)param completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'UserDataModel.userSignUp(param:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)updateUserWithParam:(NSDictionary<NSString *, id> * _Nonnull)param completion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'UserDataModel.updateUser(param:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk15UserDeviceModel")
@interface UserDeviceModel : NSObject
+ (void)getDeviceStatusWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull, NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'UserDeviceModel.getDeviceStatus(completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)getDObjectsShiftWithCompletion:(void (^ _Nonnull)(NSString * _Nonnull))completion SWIFT_DEPRECATED_OBJC("Swift method 'UserDeviceModel.getDObjectsShift(completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
+ (void)processShiftDataWithDobject:(NSDictionary * _Nonnull)dobject SWIFT_DEPRECATED_OBJC("Swift method 'UserDeviceModel.processShiftData(dobject:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk5Users")
@interface Users : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable dObjId;
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable organisationId;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19BluedolphinCloudSdk14VicinityBeacon")
@interface VicinityBeacon : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nullable addedOn;
@property (nonatomic, copy) NSString * _Nullable updatedOn;
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic, copy) NSString * _Nullable major;
@property (nonatomic, copy) NSString * _Nullable minor;
@property (nonatomic, copy) NSString * _Nullable beaconId;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable organizationId;
@property (nonatomic, copy) NSString * _Nullable placeId;
@property (nonatomic, strong) RMCLocation * _Nullable location;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
